def raise_exception(a,b)

  puts "please enter first number"
  a=gets.to_f

  puts "please enter Second number"
  b=gets.to_i


   result=a/b

   puts "result = #{result}"
  rescue

  puts 'Divisible my 0 is not allowed'

  re


end



raise_exception 10,5

